version: "3.8"

services:
  app:
    image: todo-api
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo-api
    ports:
      - "8081:8081"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=todo_user
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=todo_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./configs:/app/configs
      - ./logs:/app/logs
    networks:
      - todo-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  mysql:
    image: mysql:8.0
    container_name: todo-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=todo_db
      - MYSQL_USER=todo_user
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - todo-network
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 3s
      retries: 5

  redis:
    image: redis:6.2
    container_name: todo-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    sysctls:
      net.core.somaxconn: '512'
    command: >
      bash -c '
      echo never > /sys/kernel/mm/transparent_hugepage/enabled || true;
      echo never > /sys/kernel/mm/transparent_hugepage/defrag || true;
      sysctl -w vm.overcommit_memory=1 || true;
      redis-server --requirepass "${REDIS_PASSWORD}" --appendonly yes
      '
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - todo-network
    ulimits:
      memlock: -1

networks:
  todo-network:
    driver: bridge

volumes:
  mysql_data:
  redis_data: 