version: "3.8"

services:
  app:
    image: todo-api
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo-api
    ports:
      - "8081:8081"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=todo_user
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=todo_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mysql
      - redis
    volumes:
      - ./configs:/app/configs
      - ./logs:/app/logs
    networks:
      - todo-network

  mysql:
    image: mysql:8.0
    container_name: todo-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=todo_db
      - MYSQL_USER=todo_user
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - todo-network
    command: --default-authentication-plugin=mysql_native_password

  redis:
    image: redis:6.2
    container_name: todo-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge

volumes:
  mysql_data:
  redis_data: 