version: "3.8"

services:
  app:
    image: todo-api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
    environment:
      - TZ=Asia/Shanghai
      - DB_PASSWORD=${DB_PASSWORD:-root}
    volumes:
      - ./configs:/app/configs
      - ./logs:/app/logs

  mysql:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
      - MYSQL_DATABASE=todo_db
      - TZ=Asia/Shanghai
    volumes:
      - /data/mysql:/var/lib/mysql
      - /data/mysql/conf.d:/etc/mysql/conf.d
      - /data/mysql/logs:/var/log/mysql
    command: --default-authentication-plugin=mysql_native_password

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /data/redis:/data
      - /data/redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

networks:
  todo-network:
    driver: bridge 