# API版本和资源类型
apiVersion: v1
kind: Secret # Secret用于存储敏感信息
metadata:
  name: mysql-secret # Secret名称
  namespace: todo-app # 所属命名空间
type: Opaque # 通用Secret类型
data:
  password: cm9vdA== # MySQL root密码的base64编码(root)

---
# JWT密钥Secret
apiVersion: v1
kind: Secret # Secret用于存储敏感信息
metadata:
  name: jwt-secret # Secret名称
  namespace: todo-app # 所属命名空间
type: Opaque # 通用Secret类型
data:
  secret: eW91cl9qd3Rfc2VjcmV0X2tleQ== # JWT密钥的base64编码(your_jwt_secret_key)
