# API版本和资源类型
apiVersion: v1
kind: Service # Service用于暴露应用，提供稳定的网络访问点

# Service元数据
metadata:
  name: todo-api # Service名称
  namespace: todo-app # 所属命名空间

# Service规格
spec:
  # Pod选择器，用于确定哪些Pod属于此Service
  selector:
    app: todo-api

  # 端口配置
  ports:
    - name: http # 端口名称
      port: 80 # Service端口
      targetPort: 8080 # Pod端口

  type: ClusterIP # Service类型：集群内部访问
