server:
  mode: "release"
  port: 8081
  read_timeout: 10
  write_timeout: 10
  
mysql:
  host: mysql
  port: 3306
  username: todo_user
  password: ${DB_PASSWORD}
  database: todo_db
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: "1h"

redis:
  host: redis
  port: 6379
  password: ${REDIS_PASSWORD}
  db: 0
  pool_size: 10

jwt:
  secret: ${JWT_SECRET}
  expire_hours: 24
  issuer: "todo-api"

logger:
  level: info
  file: "/app/logs/app.log"

rate_limit:
  requests_per_second: 100
  burst: 50

task_queue:
  buffer_size: 1000
  workers: 5 