name: Deploy to Cloud

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
        
    - name: Download dependencies
      run: go mod download
        
    - name: Install swag
      run: go install github.com/swaggo/swag/cmd/swag@latest
        
    - name: Generate Swagger Docs
      run: swag init -g cmd/server/main.go --parseDependency --parseInternal --parseDepth 1
        
    - name: Build
      run: |
        CGO_ENABLED=0 GOOS=linux go build -o build/todo-api cmd/server/main.go
        
    - name: Create deployment directory
      run: |
        mkdir -p deployment/configs
        mkdir -p deployment/scripts
        cp build/todo-api deployment/
        cp configs/config.prod.yaml deployment/configs/
        cp deployments/docker/docker-compose.prod.yml deployment/docker-compose.yml
        cp deployments/docker/Dockerfile deployment/
        cp deployments/scripts/deploy.sh deployment/
        cp scripts/init.sql deployment/scripts/
        chmod +x deployment/deploy.sh
        
    - name: Copy files to server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        source: "deployment/*"
        target: "/opt/todo-api"
        strip_components: 1
        
    - name: Execute deployment script
      uses: appleboy/ssh-action@v1.0.3
      env:
        MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
        APP_ENV: prod
        LOG_LEVEL: info
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        envs: MYSQL_ROOT_PASSWORD,DB_PASSWORD,JWT_SECRET,REDIS_PASSWORD,APP_ENV,LOG_LEVEL
        script: |
          cd /opt/todo-api
          export MYSQL_ROOT_PASSWORD="${MYSQL_ROOT_PASSWORD}"
          export DB_PASSWORD="${DB_PASSWORD}"
          export JWT_SECRET="${JWT_SECRET}"
          export REDIS_PASSWORD="${REDIS_PASSWORD:-''}"
          export APP_ENV="prod"
          export LOG_LEVEL="info"
          chmod +x deploy.sh
          ./deploy.sh 