name: Deploy to Cloud

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Create deployment directory
      run: |
        mkdir -p deployment/configs
        mkdir -p deployment/scripts
        cp -r configs/ deployment/configs/
        cp -r deployments/docker/docker-compose.prod.yml deployment/docker-compose.yml
        cp -r deployments/docker/Dockerfile deployment/
        cp -r deployments/scripts/deploy.sh deployment/
        cp -r scripts/init.sql deployment/scripts/
        # 复制源代码和构建文件
        cp -r . deployment/src/
        chmod +x deployment/deploy.sh
        
    - name: Copy files to server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        source: "deployment/*"
        target: "/opt/todo-api"
        strip_components: 1
        
    - name: Setup system parameters
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          # 创建系统参数配置文件
          sudo tee /etc/sysctl.d/99-redis.conf << EOF
          vm.overcommit_memory = 1
          net.core.somaxconn = 512
          EOF
          
          # 应用系统参数
          sudo sysctl -p /etc/sysctl.d/99-redis.conf
          
          # 禁用 THP
          sudo bash -c 'echo never > /sys/kernel/mm/transparent_hugepage/enabled'
          sudo bash -c 'echo never > /sys/kernel/mm/transparent_hugepage/defrag'
          
          # 创建持久化的 THP 设置
          sudo tee /etc/systemd/system/disable-thp.service << EOF
          [Unit]
          Description=Disable Transparent Huge Pages (THP)
          
          [Service]
          Type=oneshot
          ExecStart=/bin/sh -c 'echo never > /sys/kernel/mm/transparent_hugepage/enabled && echo never > /sys/kernel/mm/transparent_hugepage/defrag'
          RemainAfterExit=yes
          
          [Install]
          WantedBy=multi-user.target
          EOF
          
          # 启用并启动服务
          sudo systemctl daemon-reload
          sudo systemctl enable disable-thp
          sudo systemctl start disable-thp
    
    - name: Execute deployment script
      uses: appleboy/ssh-action@v1.0.3
      env:
        MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_HOST: "mysql"
        DB_USER: "todo_user"
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
        APP_ENV: prod
        LOG_LEVEL: debug
        TZ: Asia/Shanghai
        BUILD_VERSION: ${{ github.sha }}
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        envs: MYSQL_ROOT_PASSWORD,DB_PASSWORD,DB_HOST,DB_USER,JWT_SECRET,REDIS_PASSWORD,APP_ENV,LOG_LEVEL,TZ,BUILD_VERSION
        script: |
          cd /opt/todo-api
          # 清理旧的镜像
          docker image prune -f
          export MYSQL_ROOT_PASSWORD="${MYSQL_ROOT_PASSWORD}"
          export DB_PASSWORD="${DB_PASSWORD}"
          export JWT_SECRET="${JWT_SECRET}"
          export REDIS_PASSWORD="${REDIS_PASSWORD:-''}"
          export APP_ENV="prod"
          export LOG_LEVEL="debug"
          export BUILD_VERSION="${BUILD_VERSION}"
          chmod +x deploy.sh
          ./deploy.sh 