name: Deploy to Cloud

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
        
    - name: Install swag
      run: go install github.com/swaggo/swag/cmd/swag@latest
        
    - name: Generate Swagger Docs
      run: swag init -g cmd/server/main.go --parseDependency --parseInternal --parseDepth 1
        
    - name: Build
      run: |
        go mod download
        CGO_ENABLED=0 GOOS=linux go build -o build/todo-api cmd/server/main.go
        
    - name: Create deployment directory
      run: |
        mkdir -p deployment
        cp build/todo-api deployment/
        cp -r configs deployment/
        cp deployments/docker/docker-compose.prod.yml deployment/docker-compose.yml
        cp deployments/scripts/deploy.sh deployment/
        chmod +x deployment/deploy.sh
        
    - name: Copy files to server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: 22
        source: "deployment/*"
        target: "/opt/todo-api"
        strip_components: 1
        
    - name: Execute deployment script
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: 22
        script: |
          cd /opt/todo-api
          chmod +x deploy.sh
          ./deploy.sh 